test:
  stage: test
  only:
    - master
  before_script:
    - pushd $HOME
    - mkdir nim && cd nim
    - curl -L 'https://nim-lang.org/download/nim-2.0.0-linux_x64.tar.xz' | tar -xJ
    - PATH="$(pwd)/nim-2.0.0/bin:$PATH"
    - popd
    - atlas install --autoinit --cfgHere
  script:
    - for f in tests/t*.nim; do nim r --verbosity:0 "$f"; done
